#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/global/homes/z/zladd/nrn-7.6/bin"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/global/homes/z/zladd/nrn-7.6/bin/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/global/cscratch1/sd/zladd/axonstandardized/playground/genetic_alg/make_models_mappings/bbp_RmpRiTau_pipeline/model_folder_L5_NBC_bSTUT213_1/x86_64/.libs/libnrnmech.so" "$@"
