#!/bin/bash -l
#SBATCH  --account m2043

#SBATCH -N 1 
#SBATCH --gres=gpu:8 -c 80  -C gpu  -t 3:59:00

#
# - - -  no SBATCH commands below this line - - - - 
srun  python optimize_parameters_genetic_alg_SG.py 
